version: '3'

services:
  seedoverflow-client:
    build: seedoverflow-client
    command: ["npm", "run", "dev"]
    volumes:
      - ./seedoverflow-client:/src
      - node-modules:/src/node_modules
    environment:
      - NODE_ENV=development
      - DEV_API=http://localhost:5000/api/v1
      - PROD_API=https://seedoverflow-prod-api.herokuapp.com/api/v1
    ports:
      - '3000:3000'
    depends_on:
      - seedoverflow-api
      - seedoverflow-database
  seedoverflow-api:
    build: seedoverflow-api
    command: ["python3", "run.py"]
    volumes:
      - ./seedoverflow-api:/backend
    environment:
      - FLASK_ENV=docker-dev
      - FLASK_APP=run.py
    env_file:
      - ./seedoverflow-api/.env
    ports:
      - "5000:5000"
    depends_on:
      - seedoverflow-database
  seedoverflow-node-api:
    build: ./seedoverflow-node-api
    restart: always
    env_file:
      - ./seedoverflow-node-api/.env
    ports:
      - "5005:5005"
    depends_on:
      - seedoverflow-database
    volumes:
      - ./seedoverflow-node-api:/user/src/app
  seedoverflow-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seedoverflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # - ./seedoverflow-api/schema/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  node-modules: