name: Python Unittests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: seedoverflow-api
    - name: Run tests
      run: |
        test-api.sh
      working-directory: seedoverflow-api
=======
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: seedoverflow-api
      - name: Run tests
        run: |
          test-api.sh
        working-directory: seedoverflow-api
>>>>>>> d392745628f509f10a59c00d9e67f7d25925c713
